version: '3.7'  # if no version is specificed then v1 is assumed. Recommend v2 minimum

services:    
  pdfg-base:
    image: inleague/coldfusion_pdfg:acf11
    build:
      context: ./config/
      labels:
        version: 2018.09.25